Repository Scratch-Bookmarklets/Scratch-Bookmarklets.github.io, pull requests merged in 2021-05, with the labels that each got.

#11 Fix README.md link
  README.md
Labels: documentation

#26 Favicon
  scratchbookmarklets.png
Labels: Medium Priority, enhancement

#127 Patch 5: Updates Website
  contributors.html
Labels: pr-status: good to merge

#132 Patch 6: Lots of commits plus a new bookmarklet
  bookmarklets/bookmarklets.json
  bookmarklets/open-forkphorus/bookmarklet.js
  bookmarklets/open-forkphorus/manifest.json
Labels: pr-status: good to merge

#133 Prettier
  .github/ISSUE_TEMPLATE/Bug_Report.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .github/ISSUE_TEMPLATE/Question.md
  .github/workflows/prettier.yml
  .prettierignore
  404.html
  CODE_OF_CONDUCT.md
  README.md
  about.html
  assets/css/style.css
  assets/js/script.js
  assets/json/package.json
  bookmarklets.html
  bookmarklets/bookmarklets.json
  bookmarklets/display-stage-on-left/bookmarklet.js
  bookmarklets/open-forkphorus/bookmarklet.js
  bookmarklets/open-phosphorus/bookmarklet.js
  bookmarklets/open-turbowarp/bookmarklet.js
  contributors.html
  index.html
  projects.html
Labels: pr-status: needs-review

#137 update prettier commit message and greet contribs message
  .github/workflows/greet-contributors.yml
  .github/workflows/prettier.yml
Labels: pr-status: good to merge

#138 replace probot stale with action stale
  .github/workflows/actions-stale.yml
  .github/workflows/stale.yml
Labels: pr-status: approved
